### ISSUE TITLE
does not work  on OS X 

### ISSUE THREAD

**Issue by antfp** [almero-digital-marketing/docpad-plugin-copy#2]
this plugin does not work on OS X 10.10. gives an error about xcopy.

**Comment by dimitarkolev** [comment]
Fixed pushed to github and npm.

**Comment by antfp** [comment]
I'm afraid it still doesn't work. Now the error message is:

error: Copying error Error: /bin/cp: illegal option -- u
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory

Thank you!

**Comment by dimitarkolev** [comment]
Just pushed another update, can you try it. It now uses rsync instead of cp on OSX in order to copy only changed files.
On linux cp -u option copy files only when the source file is newer than the destination file or when the destination file is missing, unfortunately its not available on OSX thats why we had to use rsync. 
Its supposed to be even better solution I believe.

**Comment by antfp** [comment]
Now it seems to work just fine. Changed a file inside the raw directory and it detected that change and made the copy fast. 
Thank you for your support!
